(function(){
  const P=window.PaperClip,U=window.PaperClipUtils;let rows=[],charts=[];
  P.setTitle('Analytics','Explore the tracker from several angles');
  const root=document.getElementById('page-root');root.innerHTML=`<section class="panel rounded-2xl p-4"><div class="grid gap-3 sm:grid-cols-3"><label><span class="muted mb-1 block text-xs font-bold">Domain</span><select id="domain" class="select"><option value="">All domains</option></select></label><label><span class="muted mb-1 block text-xs font-bold">Assignee</span><select id="assignee" class="select"><option value="">All assignees</option></select></label><label><span class="muted mb-1 block text-xs font-bold">Month | Year</span><select id="month" class="select"><option value="">All months</option></select></label></div></section><section id="charts" class="mt-5 grid gap-5 xl:grid-cols-2"></section>`;
  const el=id=>document.getElementById(id),group=(list,key)=>list.reduce((o,p)=>{const k=U.text(p[key])||'Unspecified';o[k]=(o[k]||0)+1;return o},{}),colors=['#098077','#105b5d','#d4af37','#327f76','#6d8f8c','#b8962e','#185052','#79aaa4'];
  function filtered(){return rows.filter(p=>(!el('domain').value||p.DOMAIN===el('domain').value)&&(!el('assignee').value||p.ASSIGNEE===el('assignee').value)&&(!el('month').value||p.MONTH_YEAR===el('month').value))}
  function make(id,type,data){const entries=Object.entries(data);return new Chart(document.getElementById(id),{type,data:{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),backgroundColor:colors,borderColor:'#098077',borderWidth:type==='line'?2:0,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'||type==='pie'}},scales:['doughnut','pie'].includes(type)?{}:{x:{ticks:{color:'#738382'},grid:{display:false}},y:{ticks:{color:'#738382'},grid:{color:'rgba(16,91,93,.14)'}}}}})}
  function render(){charts.forEach(c=>c.destroy());const list=filtered(),s=list.reduce((o,p)=>{const k=U.status(p);o[k]=(o[k]||0)+1;return o},{});el('charts').innerHTML=[['month-chart','Papers by month'],['assignee-chart','Papers by assignee'],['status','Workflow status'],['domain-chart','Domain distribution']].map(([id,title])=>`<article class="panel rounded-2xl p-4"><h2 class="font-extrabold">${title}</h2><p class="muted text-xs">${list.length} matching papers</p><div class="chart-box mt-3"><canvas id="${id}"></canvas></div></article>`).join('');charts=[make('month-chart','line',group(list,'MONTH_YEAR')),make('assignee-chart','bar',group(list,'ASSIGNEE')),make('status','doughnut',{Completed:s.done||0,Pending:s.pending||0,Review:s.review||0}),make('domain-chart','bar',group(list,'DOMAIN'))]}
  function hydrate(data){rows=data;[['domain','DOMAIN','All domains'],['assignee','ASSIGNEE','All assignees'],['month','MONTH_YEAR','All months']].forEach(([id,key,label])=>el(id).innerHTML=`<option value="">${label}</option>`+U.unique(rows,key).map(v=>`<option>${U.esc(v)}</option>`).join(''));render()}
  ['domain','assignee','month'].forEach(id=>el(id).onchange=render);window.addEventListener('paperclip:data',e=>hydrate(e.detail));P.refresh();
})();
