(function(){
  const U=window.PaperClipUtils, A=window.PaperClipAPI;
  const nav=[['dashboard.html','dashboard','Dashboard','▦'],['month-view.html','month-view','Monthly View','◷'],['search.html','search','Master Tracker','⌕'],['assignee.html','assignee','Assignees','♙'],['analytics.html','analytics','Analytics','◒']];
  const state={papers:[],page:document.body.dataset.page||'dashboard'};
  function shell(){
    document.body.insertAdjacentHTML('afterbegin',`<aside id="sidebar" class="panel fixed inset-y-0 left-0 z-50 w-64 border-y-0 border-l-0 p-4"><div class="flex h-full flex-col"><a href="dashboard.html" class="mb-8 flex items-center gap-3 px-2"><img class="brand-mark" src="assets/badge.png" alt="Paper Clip badge"><span><b class="block text-lg">Paper <span class="brand-gold">Clip</span></b><small class="muted">Research workspace</small></span></a><nav class="space-y-1">${nav.map(([href,id,label,icon])=>`<a class="sidebar-link ${id===state.page?'active':''}" href="${href}"><span class="w-5 text-center">${icon}</span>${label}</a>`).join('')}</nav><div class="api-card mt-auto rounded-2xl p-3 text-xs muted"><b class="mb-1 block">Paper Clip API</b><span id="connection-label">Connecting to tracker...</span></div></div></aside><div class="main-shell min-h-screen lg:ml-64"><header class="sticky top-0 z-30 border-b border-slate-300/20 bg-white/60 px-4 py-3 backdrop-blur-xl dark:bg-slate-950/60 sm:px-6"><div class="flex items-center justify-between gap-3"><div class="flex items-center gap-3"><button id="menu-btn" class="icon-btn lg:hidden" aria-label="Open menu">☰</button><div><h1 id="page-title" class="text-lg font-extrabold"></h1><p id="page-subtitle" class="muted text-xs"></p></div></div><div class="flex items-center gap-2"><button id="global-search" class="btn btn-soft hidden sm:inline-flex">⌕ Search</button><button id="theme-btn" class="icon-btn" aria-label="Toggle theme">◐</button><button data-add-paper class="btn btn-primary">＋ Add paper</button></div></div></header><main id="page-root" class="p-4 sm:p-6"></main></div><div id="toast-root" class="fixed right-4 top-20 z-[80] space-y-2"></div><div id="modal-root"></div>`);
    document.getElementById('menu-btn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
    document.getElementById('theme-btn').onclick=toggleTheme;
    document.getElementById('global-search').onclick=()=>location.href='search.html';
    document.querySelectorAll('[data-add-paper]').forEach(b=>b.onclick=()=>openPaperModal());
  }
  function setTitle(title,subtitle){document.getElementById('page-title').textContent=title;document.getElementById('page-subtitle').textContent=subtitle}
  function toast(message,type='info',ms=3200){const el=document.createElement('div');el.className=`toast panel rounded-xl px-4 py-3 text-sm ${type}`;el.textContent=message;document.getElementById('toast-root').append(el);setTimeout(()=>el.remove(),ms)}
  function applyTheme(){document.documentElement.classList.toggle('dark',localStorage.getItem('paperclip.theme')==='dark')}
  function toggleTheme(){localStorage.setItem('paperclip.theme',document.documentElement.classList.contains('dark')?'light':'dark');applyTheme();window.dispatchEvent(new CustomEvent('paperclip:theme'))}
  function skeleton(){return `<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${Array.from({length:4},()=>'<div class="skeleton h-28"></div>').join('')}</div><div class="skeleton mt-6 h-80"></div>`}
  function empty(title='No papers found',note='Try changing the filters or add a new paper.'){return `<div class="py-14 text-center"><div class="mb-3 text-4xl">⌕</div><h3 class="font-bold">${U.esc(title)}</h3><p class="muted mt-1 text-sm">${U.esc(note)}</p></div>`}
  function badge(paper){const s=U.status(paper),label=s==='done'?'Done':s==='review'?'Review':'Pending';return `<span class="badge badge-${s}">${label}</span>`}
  function table(rows,{query='',actions=true,limit}={}){
    const list=limit?rows.slice(0,limit):rows;if(!list.length)return empty();
    return `<div class="table-wrap"><table class="data-table"><thead><tr>${U.FIELDS.map(f=>`<th>${U.esc(U.LABELS[f])}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${list.map(p=>`<tr>${U.FIELDS.map(f=>`<td title="${U.esc(p[f])}">${f==='PAPER_TITLE'?U.highlight(p[f],query):f==='WORK_STAGE'?badge(p):U.highlight(p[f],query)}</td>`).join('')}${actions?`<td><div class="flex gap-1">${U.text(p.ID)?`<button class="icon-btn" title="Edit paper" data-edit="${U.esc(p.ID)}">✎</button>`:''}${U.safeUrl(p.LINK)?`<a class="icon-btn" target="_blank" rel="noopener" href="${U.esc(U.safeUrl(p.LINK))}" title="Open link">↗</a>`:''}${U.text(p.ID)?`<button class="icon-btn text-red-500" title="Delete paper" data-delete="${U.esc(p.ID)}">×</button>`:''}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`;
  }
  function bindTableActions(container=document){container.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openPaperModal(state.papers.find(p=>p.ID===b.dataset.edit)));container.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.delete))}
  function formFields(p={}){return U.FIELDS.filter(f=>f!=='ID').map(f=>`<label class="${['PAPER_TITLE','ABSTRACT','NOTES','DATASET'].includes(f)?'sm:col-span-2':''}"><span class="muted mb-1 block text-xs font-bold">${U.esc(U.LABELS[f])}${f==='PAPER_TITLE'?' *':''}</span>${['ABSTRACT','NOTES','DATASET'].includes(f)?`<textarea class="textarea" rows="3" name="${f}">${U.esc(p[f])}</textarea>`:`<input class="input" name="${f}" value="${U.esc(p[f])}" ${f==='PAPER_TITLE'?'required':''}>`}</label>`).join('')}
  function openPaperModal(paper){const edit=Boolean(paper),root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-backdrop"></div><section class="modal panel rounded-3xl p-5 fade-in"><div class="mb-4 flex items-start justify-between"><div><h2 class="text-xl font-extrabold">${edit?'Edit paper':'Add paper'}</h2><p class="muted text-xs">${edit?U.esc(paper.ID):'A tracker ID will be generated automatically.'}</p></div><button data-close class="icon-btn">×</button></div><form id="paper-form" class="grid gap-3 sm:grid-cols-2">${formFields(paper)}<div class="mt-3 flex justify-end gap-2 sm:col-span-2"><button type="button" data-close class="btn btn-soft">Cancel</button><button class="btn btn-primary" type="submit">${edit?'Save changes':'Add paper'}</button></div></form></section>`;root.querySelectorAll('[data-close],.modal-backdrop').forEach(e=>e.onclick=()=>root.innerHTML='');root.querySelector('form').onsubmit=async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));if(!U.text(data.PAPER_TITLE))return toast('Paper title is required.','error');if(edit)data=Object.fromEntries(Object.entries(data).filter(([key,value])=>String(paper[key]??'')!==value));if(edit&&!Object.keys(data).length)return toast('No changes to save.','warning');try{toast(edit?'Saving changes...':'Adding paper...');edit?await A.updatePaper(paper.ID,data):await A.addPaper(data);root.innerHTML='';toast(edit?'Paper updated.':'Paper added.','success');await refresh()}catch(err){toast(err.message,'error',5000)}};
  }
  function confirmDelete(id){const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-backdrop"></div><section class="modal panel max-w-md rounded-3xl p-5 fade-in"><h2 class="text-xl font-extrabold">Delete ${U.esc(id)}?</h2><p class="muted mt-2 text-sm">This removes the paper from the shared tracker.</p><div class="mt-5 flex justify-end gap-2"><button data-close class="btn btn-soft">Cancel</button><button id="confirm-delete" class="btn bg-red-600 text-white">Delete paper</button></div></section>`;root.querySelectorAll('[data-close],.modal-backdrop').forEach(e=>e.onclick=()=>root.innerHTML='');document.getElementById('confirm-delete').onclick=async()=>{try{await A.deletePaper(id);root.innerHTML='';toast('Paper deleted.','success');await refresh()}catch(err){toast(err.message,'error',5000)}}}
  async function loadPapers(){const cached=A.readCache();if(cached?.data){state.papers=cached.data;window.dispatchEvent(new CustomEvent('paperclip:data',{detail:state.papers}))}state.papers=await A.getAllPapers();document.getElementById('connection-label').textContent='Live tracker connected';window.dispatchEvent(new CustomEvent('paperclip:data',{detail:state.papers}));return state.papers}
  async function refresh(){try{await loadPapers()}catch(err){document.getElementById('connection-label').textContent='Offline: cached data unavailable';toast(err.message,'error',5000);window.dispatchEvent(new CustomEvent('paperclip:data',{detail:state.papers}));window.dispatchEvent(new CustomEvent('paperclip:error',{detail:err}))}}
  function shortcuts(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();location.href='search.html'}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();openPaperModal()}if(e.key==='Escape')document.getElementById('modal-root').innerHTML=''})}
  window.addEventListener('paperclip:offline',()=>{document.getElementById('connection-label').textContent='Showing cached tracker data';toast('Network unavailable. Showing cached papers.','warning')});
  applyTheme();shell();shortcuts();
  window.PaperClip={state,setTitle,toast,skeleton,empty,table,bindTableActions,refresh,badge};
})();
