(function(){
  const P=window.PaperClip,U=window.PaperClipUtils;let rows=[],chart;
  P.setTitle('Assignees','Personal workload and completion overview');
  const root=document.getElementById('page-root');root.innerHTML=`<section class="panel rounded-2xl p-4"><div class="flex flex-wrap items-end justify-between gap-3"><label class="w-full max-w-sm"><span class="muted mb-1 block text-xs font-bold">Select assignee</span><select id="person" class="select"></select></label><button id="export" class="btn btn-soft">↓ Export assignee CSV</button></div></section><section id="assignee-content" class="mt-5"></section>`;
  const person=document.getElementById('person'),content=document.getElementById('assignee-content');
  function render(){const name=person.value,list=rows.filter(p=>p.ASSIGNEE===name),count=k=>list.reduce((n,p)=>n+(U.status(p)===k),0);chart?.destroy();content.innerHTML=`<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${[['Assigned',list.length],['Completed',count('done')],['Pending',count('pending')],['Review',count('review')]].map(([l,v])=>`<article class="panel rounded-2xl p-5"><span class="muted text-xs font-bold uppercase">${l}</span><b class="mt-2 block text-3xl">${v}</b></article>`).join('')}</div><div class="mt-5 grid gap-5 xl:grid-cols-[320px_1fr]"><article class="panel rounded-2xl p-4"><h2 class="font-extrabold">Workload split</h2><div class="chart-box mt-3"><canvas id="assignee-chart"></canvas></div></article><article class="panel rounded-2xl"><div class="p-4"><h2 class="font-extrabold">${U.esc(name||'Assignee')} papers</h2></div>${P.table(list)}</article></div>`;chart=new Chart(document.getElementById('assignee-chart'),{type:'doughnut',data:{labels:['Completed','Pending','Review'],datasets:[{data:[count('done'),count('pending'),count('review')],backgroundColor:['#098077','#105b5d','#d4af37']}]},options:{responsive:true,maintainAspectRatio:false}});P.bindTableActions(content)}
  function hydrate(data){rows=data;const names=U.unique(rows,'ASSIGNEE');person.innerHTML=names.map(n=>`<option>${U.esc(n)}</option>`).join('');render()}
  person.onchange=render;document.getElementById('export').onclick=()=>U.download(rows.filter(p=>p.ASSIGNEE===person.value),`${person.value||'assignee'}-papers.csv`);window.addEventListener('paperclip:data',e=>hydrate(e.detail));P.refresh();
})();
