(function(){
  const P=window.PaperClip,U=window.PaperClipUtils;let charts=[];
  P.setTitle('Dashboard','A quick view of the research pipeline');
  const root=document.getElementById('page-root');root.innerHTML=P.skeleton();
  const count=(rows,key)=>rows.reduce((n,p)=>n+(U.status(p)===key),0);
  const group=(rows,key)=>rows.reduce((o,p)=>{const k=U.text(p[key])||'Unspecified';o[k]=(o[k]||0)+1;return o},{});
  const chart=(id,type,labels,data,colors)=>new Chart(document.getElementById(id),{type,data:{labels,datasets:[{data,backgroundColor:colors,borderColor:'#098077',borderWidth:type==='line'?2:0,tension:.35,fill:type==='line'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type!=='bar'&&type!=='line',labels:{color:getComputedStyle(document.body).color}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#738382'},grid:{display:false}},y:{ticks:{color:'#738382'},grid:{color:'rgba(16,91,93,.14)'}}}}});
  function render(rows){
    charts.forEach(c=>c.destroy());charts=[];
    const stats=[['Total papers',rows.length,'bg-teal-600/15 text-teal-600'],['Completed',count(rows,'done'),'bg-teal-500/15 text-teal-600'],['Pending',count(rows,'pending'),'bg-cyan-900/15 text-cyan-800'],['Under review',count(rows,'review'),'bg-yellow-500/15 text-yellow-600']];
    const monthly=group(rows,'MONTH_YEAR'),assignees=group(rows,'ASSIGNEE'),statuses={Completed:count(rows,'done'),Pending:count(rows,'pending'),Review:count(rows,'review')};
    root.innerHTML=`<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${stats.map(([label,value,color])=>`<article class="panel rounded-2xl p-5"><span class="muted text-xs font-bold uppercase tracking-wider">${label}</span><div class="mt-3 flex items-end justify-between"><b class="text-3xl">${value}</b><span class="rounded-xl px-3 py-2 ${color}">●</span></div></article>`).join('')}</section><section class="mt-5 grid gap-5 xl:grid-cols-3"><article class="panel rounded-2xl p-4 xl:col-span-2"><h2 class="font-extrabold">Papers by month</h2><div class="chart-box mt-3"><canvas id="month-chart"></canvas></div></article><article class="panel rounded-2xl p-4"><h2 class="font-extrabold">Workflow status</h2><div class="chart-box mt-3"><canvas id="status-chart"></canvas></div></article></section><section class="mt-5 grid gap-5 xl:grid-cols-[1fr_280px]"><article class="panel rounded-2xl"><div class="flex items-center justify-between p-4"><div><h2 class="font-extrabold">Recent papers</h2><p class="muted text-xs">Latest entries from the master tracker</p></div><a class="btn btn-soft" href="search.html">View tracker</a></div>${P.table([...rows].reverse(),{limit:8})}</article><aside class="panel rounded-2xl p-4"><h2 class="font-extrabold">Quick actions</h2><div class="mt-4 grid gap-2"><button data-quick-add class="btn btn-primary">＋ Add paper</button><a class="btn btn-soft" href="month-view.html">◷ Browse by month</a><a class="btn btn-soft" href="search.html">⌕ Search tracker</a><button data-export class="btn btn-soft">↓ Export CSV</button></div><div class="mt-6"><h3 class="muted text-xs font-bold uppercase tracking-wider">Keyboard shortcuts</h3><p class="muted mt-2 text-xs"><b>Ctrl N</b> add paper<br><b>Ctrl K</b> search tracker</p></div></aside></section>`;
    const m=Object.keys(monthly),a=Object.entries(assignees).sort((x,y)=>y[1]-x[1]).slice(0,10);
    charts=[chart('month-chart','line',m,m.map(k=>monthly[k]),'rgba(9,128,119,.2)'),chart('status-chart','doughnut',Object.keys(statuses),Object.values(statuses),['#098077','#105b5d','#d4af37'])];
    P.bindTableActions(root);root.querySelector('[data-quick-add]').onclick=()=>document.querySelector('[data-add-paper]').click();root.querySelector('[data-export]').onclick=()=>U.download(rows);
  }
  window.addEventListener('paperclip:data',e=>render(e.detail));window.addEventListener('paperclip:theme',()=>P.refresh());P.refresh();
})();
