(function(){
  const P=window.PaperClip,U=window.PaperClipUtils;let rows=[],page=1;const size=25;
  P.setTitle('Master Tracker','Search, filter, edit, and export every paper');
  const root=document.getElementById('page-root');
  root.innerHTML=`<section class="panel rounded-2xl p-4"><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-7"><label class="xl:col-span-2"><span class="muted mb-1 block text-xs font-bold">Search title, ID, or assignee</span><input id="query" class="input" placeholder="Start typing or press Ctrl K..."></label>${[['assignee','Assignee'],['stage','Work stage'],['domain','Domain'],['month','Month | Year']].map(([id,l])=>`<label><span class="muted mb-1 block text-xs font-bold">${l}</span><select id="${id}" class="select"><option value="">All</option></select></label>`).join('')}<label><span class="muted mb-1 block text-xs font-bold">Sort by</span><select id="sort" class="select"><option value="month">Month</option><option value="priority">Priority</option><option value="stage">Work stage</option><option value="assignee">Assignee</option></select></label></div><div class="mt-3 flex flex-wrap items-center justify-between gap-2"><p id="result-count" class="muted text-xs"></p><div class="flex gap-2"><button id="clear" class="btn btn-soft">Clear filters</button><button id="export" class="btn btn-soft">↓ Export CSV</button></div></div></section><section id="results" class="panel mt-5 rounded-2xl"></section><div id="pager" class="mt-4 flex items-center justify-between"></div>`;
  const el=id=>document.getElementById(id),filters=['assignee','stage','domain','month'],sortKeys={month:'MONTH_YEAR',priority:'PRIORITY',stage:'WORK_STAGE',assignee:'ASSIGNEE'};
  function option(id,values){el(id).innerHTML='<option value="">All</option>'+values.map(v=>`<option>${U.esc(v)}</option>`).join('')}
  function filtered(){
    const q=U.text(el('query').value).toLowerCase();
    const f=Object.fromEntries(filters.map(k=>[k,el(k).value]));
    return rows.filter(p=>(!q||[p.PAPER_TITLE,p.ID,p.ASSIGNEE].some(v=>U.text(v).toLowerCase().includes(q)))&&(!f.assignee||p.ASSIGNEE===f.assignee)&&(!f.stage||p.WORK_STAGE===f.stage)&&(!f.domain||p.DOMAIN===f.domain)&&(!f.month||p.MONTH_YEAR===f.month)).sort((a,b)=>U.text(a[sortKeys[el('sort').value]]).localeCompare(U.text(b[sortKeys[el('sort').value]])));
  }
  function render(){const list=filtered(),pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages);const shown=list.slice((page-1)*size,page*size);el('result-count').textContent=`${list.length} paper${list.length===1?'':'s'} found`;el('results').innerHTML=P.table(shown,{query:el('query').value});el('pager').innerHTML=`<button id="prev" class="btn btn-soft" ${page===1?'disabled':''}>← Previous</button><span class="muted text-xs">Page ${page} of ${pages}</span><button id="next" class="btn btn-soft" ${page===pages?'disabled':''}>Next →</button>`;el('prev').onclick=()=>{page--;render()};el('next').onclick=()=>{page++;render()};P.bindTableActions(el('results'))}
  function hydrate(data){rows=data;option('assignee',U.unique(rows,'ASSIGNEE'));option('stage',U.unique(rows,'WORK_STAGE'));option('domain',U.unique(rows,'DOMAIN'));option('month',U.unique(rows,'MONTH_YEAR'));render()}
  el('query').value=localStorage.getItem('paperclip.lastSearch')||'';el('query').oninput=U.debounce(()=>{page=1;render();const q=U.text(el('query').value);localStorage.setItem('paperclip.lastSearch',q)},180);[...filters,'sort'].forEach(id=>el(id).onchange=()=>{page=1;render()});el('clear').onclick=()=>{el('query').value='';localStorage.removeItem('paperclip.lastSearch');filters.forEach(id=>el(id).value='');render()};el('export').onclick=()=>U.download(filtered(),'paper-clip-tracker.csv');
  window.addEventListener('paperclip:data',e=>hydrate(e.detail));P.refresh();
})();
